// Package history provides storage, retrieval, and export of cron job
// execution records.
//
// # CSV Export
//
// The Store type exposes two export helpers:
//
//	// Export records for a single job:
//	err := store.ExportCSV("my-job", os.Stdout)
//
//	// Export records for all known jobs:
//	err := store.ExportAllCSV(os.Stdout)
//
// Both methods write a CSV with the following columns:
//
//	job_name   – name of the cron job
//	started_at – RFC3339 UTC timestamp of when the run began
//	duration_ms – wall-clock duration of the run in milliseconds
//	success    – whether the run completed without error
//
// The output is suitable for piping into spreadsheet tools or archiving
// alongside periodic reports generated by the report package.
package history
